version: '3.8'

services:
  app:
    build: .
    expose:
      - "8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/expenses_tracker?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Test@123

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"  # Changed from 80:80 to 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=expenses_tracker
      - MYSQL_ROOT_PASSWORD=Test@123
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql_script.sql:/docker-entrypoint-initdb.d/sql_script.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pTest@123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql-data:

volumes:
  mysql-data:
